const CINEMA_NAMES = {
    FILM: 'FILM',
    TV_SERIES: 'TV_SERIES',
    TOP_POPULAR_ALL: 'TOP_POPULAR_ALL',
    TOP_250_MOVIES:	'TOP_250_MOVIES',
    TOP_250_TV_SHOWS: 'TOP_250_TV_SHOWS',
}

export { 
    CINEMA_NAMES,
}